import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import BasicSteps from "@/components/BasicSteps";
import Steps from "@/components/shared/Steps";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Salsa Steps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Salsa Steps</h1>
        <BasicSteps
          title={"Basic Steps"}
          description={
            "The Basic Steps of Cuban Salsa involve understanding the rhytmn and timing of music. Every musical rhythmn is comprised of 8 beats. The Basic Steps involve stepping on beats 1, 2, 3 and 5, 6, 7."
          }
        />
      </main>
    </>
  );
}
